package com.sipdasrh.ews.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SpasAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpasAllPropertiesEquals(Spas expected, Spas actual) {
        assertSpasAutoGeneratedPropertiesEquals(expected, actual);
        assertSpasAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpasAllUpdatablePropertiesEquals(Spas expected, Spas actual) {
        assertSpasUpdatableFieldsEquals(expected, actual);
        assertSpasUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpasAutoGeneratedPropertiesEquals(Spas expected, Spas actual) {
        assertThat(actual)
            .as("Verify Spas auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpasUpdatableFieldsEquals(Spas expected, Spas actual) {
        assertThat(actual)
            .as("Verify Spas relevant properties")
            .satisfies(a -> assertThat(a.getNamaSpas()).as("check namaSpas").isEqualTo(expected.getNamaSpas()))
            .satisfies(a -> assertThat(a.getNamaManufaktur()).as("check namaManufaktur").isEqualTo(expected.getNamaManufaktur()))
            .satisfies(a -> assertThat(a.getTipeSpas()).as("check tipeSpas").isEqualTo(expected.getTipeSpas()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpasUpdatableRelationshipsEquals(Spas expected, Spas actual) {
        // empty method
    }
}
